config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'

  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :profiles
      get :chats
    end
  end
  
  
  
  resources :posts, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:index,:create,:show,:destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    flash[:success] = '投稿をお気に入りしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    post = Post.find(params[:id])
    current_user.unlike(post)
    flash[:success] = '投稿のお気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/views/favorites/_favorite_button.html.erb
<style>
  .like-btn {
 width: 25px;
 height: 30px;
 font-size: 25px;
 color: #808080; 
 margin-left: 20px;
 }

.unlike-btn {
 width: 25px;
 height: 30px;
 font-size: 25px;
 color: #e54747;
 margin-left: 20px;
 }
</style>
<% if current_user.likes?(post) %>
 <%= link_to favorite_path(id: post.id), method: :delete do %>
    <i class="fas fa-heart unlike-btn"></i>
  <% end %>
  <% else %>
  <%= link_to favorites_path(post_id: post.id), method: :post do %>
    <i class="far fa-heart like-btn" ></i>
  <% end %>
  <% end %>