config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'

  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :profiles
      get :chats
    end
  end
  
  
  
  resources :posts, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:index,:create,:show,:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduce, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :address, length: { maximum: 50 }
  
  has_secure_password
  has_many :posts
  has_many :favorites
  has_many :likes, through: :favorites, source: :post, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def like(post)
     self.favorites.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
   favorite = self.favorites.find_by(post_id: post.id)
   favorite.destroy if favorite
  end
  
  def likes?(post)
    self.likes.include?(post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :followings, :followers, :likes, :profiles]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        render action: :profiles
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end   
    else
    redirect_to root_url
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
    counts(@user)
  end
  
  def profiles
    @user = User.find(params[:id])
  end
  
  def chats
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :sex, :address, :gym, :reason, :history, :introduce)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<style>
   body {
      background-image: url("<%= asset_path('joitra20.jpg') %>");
      background-size: cover;
    }
    
  .list-unstyled {
    margin-top:75px;
  }
</style
 <header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="<%= user_path(current_user) %>">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<style>
header {
  padding:16px;
}
  .main {
    margin-top:100px;
  }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :age, '年齢', class:'control-label' %>
        <%= f.select :age, [["",""], ["10代","10代"], ["20代","20代"], ["30代","30代"], ["40代","40代"], ["50代","50代"], ["60代","60代"], ["70代以上","70代"]], {},   class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :sex, '性別', class:'control-label' %>
        <%= f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {},   class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :address, '地域' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

     <div class="form-group">
        <%= f.label :gym, '通っているジム' %>
        <%= f.text_field :gym, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :reason, 'トレーニング目的' %>
        <%= f.text_field :reason, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :history, 'トレーニング歴' %>
        <%= f.text_field :history, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduce, '自己紹介' %>
        <%= f.text_area :introduce, :maxlength => "100", :size => "80x5",  class: 'form-control'  %>
     </div>

      <div class="al-c"><%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary' %></div>
    <% end %>
</div>
</div>
 

app/views/users/followers.html.erb
<style>
header {
  padding:16px;
}
  .main {
    margin-top:100px;
  }
  
  .card-title {
    color:#000;
  }
  body {
      background-image: url("<%= asset_path('joitra11.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <% unless current_user == @user %>
    <%= link_to 'chat', chats_user_path(@user), class: 'btn btn-warning btn-block' %>
    <% end %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link">profile</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">post  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">like  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">follow  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">follower  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>
</div>

app/views/users/followings.html.erb
<style>
header {
  padding:16px;
}
  .main {
    margin-top:100px;
  }
  
  .card-title {
    color:#000;
  }
  body {
      background-image: url("<%= asset_path('joitra11.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <% unless current_user == @user %>
    <%= link_to 'chat', chats_user_path(@user), class: 'btn btn-warning btn-block' %>
    <% end %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link">profile</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">post  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">like  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">follow  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">follower  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<style>
header {
  padding:16px;
}
  .main {
    margin-top:100px;
  }
  
  .card-title {
    color:#000;
  }
  body {
      background-image: url("<%= asset_path('joitra20.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <% unless current_user == @user %>
    <%= link_to 'chat', chats_user_path(@user), class: 'btn btn-warning btn-block' %>
    <% end %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link">profile</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">post  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">like  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">follow  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">follower  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @likes %>
  </div>
</div>
</div

app/views/users/new.html.erb
<head>
    <link href="users_new.css" rel="stylesheet">
</head>
<style>
　header {
        padding:16px;
   }
  
  .text-center {
        margin-top:100px;
    }
  
   body {
      background-image: url("<%= asset_path('joitra5.jpg') %>");
      background-size: cover;
    }
    
</style>
<header class="masthead mb-auto">
    <div class="inner">
      <!-- <h3 class="masthead-brand">Cover</h3> -->
      <h3 class="masthead-brand">JOITRA</h3>
      <nav class="nav nav-masthead justify-content-center">
        <!-- <a class="nav-link active" href="#">Home</a> -->
        <a class="nav-link" href="/">home</a>
        <!-- <a class="nav-link" href="#">Features</a> -->
        <a class="nav-link" href="login">login</a>
        <!-- <a class="nav-link" href="#">Contact</a> -->
        <a class="nav-link active" href="signup">signup</a>
      </nav>
    </div>
</header>
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/profiles.html.erb
<style>
　header {
  padding:16px;
}
  .main {
    margin-top:100px;
  }
  body {
      background-image: url("<%= asset_path('joitra9.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  <aside class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body al-c">
          <% if @user.image? %>
            <%= image_tag @user.image, :class => "mw50" %>
          <% else %>
          <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
          <% end %>
      </div>
    </div>
  </aside>
  <div class="col-md-8">
  <br>
<h2>ユーザー情報</h2>
<hr>
<p>名前：<%= @user.name %></p>
<p>年齢：<%= @user.age %>代</p>
<p>性別：<%= @user.sex %></p>
<p>地域：<%= @user.address %></p>
<p>通っているジム：<%= @user.gym %></p>
<p>トレーニング目的：<%= @user.reason %></p>
<p>トレーニング歴：<%= @user.history %></p>
<p>自己紹介：<%= @user.introduce %></p>
<% if current_user == @user %>
  <a href="<%= edit_user_path(@user) %>" class="btn btn-success">ユーザー情報を編集する</a>
<% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<style>
  header {
    width:100%;
  }
  .main {
    margin-top:132px;
  }
  .card-title {
    color:#000;
  }
  body {
      background-image: url("<%= asset_path('joitra20.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <% unless @user.id == current_user.id %>
  <% if @isRoom == true %>
    <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn btn-warning btn-block  user-show-chat"%>
    <% end %>
  <% end %>
<% end %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link">profile</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">post  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">like  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">follow  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">follower  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>
</div>