config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'

  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :profiles
      get :chats
    end
  end
  
  
  
  resources :posts, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:index,:create,:show,:destroy]
end

app/models/room.rb
class Room < ApplicationRecord
   has_many :entries, dependent: :destroy
   has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :require_user_logged_in

  def index
    @user = current_user
    @currentEntries = current_user.entries
    #@currentEntriesのルームを配列にする
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    #@currentEntriesのルーム且つcurrent_userでないEntryを新着順で取ってくる
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: @user.id).order(created_at: :desc)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
      room = Room.find(params[:id])
      room.destroy
      redirect_to rooms_path
  end
end

app/views/rooms/index.html.erb
<style>
   body {
      background-image: url("<%= asset_path('joitra8.jpg') %>");
      background-size: cover;
    }
    .main {
    margin-top:100px;
  }
  .color {
      color:white;
  }
    
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<h2>メッセージ一覧</h2>
<% @anotherEntries.each do |e| %>
    <table class="table table-striped">
        <tr>
            <td>
　　　　　　　　　<!-- 名前からroomの詳細に飛べるようにリンク化 -->
                <%= link_to room_path(e.room.id) do %>
                    <%= e.user.name %>
                <% end %>
            </td>
            <td class="color">
               <!-- 最新メッセージ内容の最初の7文字を表示する -->
               <% message = Message.find_by(id: e.room.message_ids.last) %>
               <% if message.nil? %>
               <% else %>
               <% dm = message.content %>
               <%= truncate(dm, length: 10) %>
               <% end %>
            </td>
            <td>
                <h6 style="color: #C0C0C0;"><%= e.updated_at.strftime("%Y/%m/%d %H:%M") %></h6>
            </td>
            <td>
               <!-- ゴミ箱アイコンクリックでroomを消せるようにする -->
                <%= link_to room_path(e.room.id), method: :delete do %>
                    <i class="fas fa-trash" style="color:white;"></i>
                <% end %>
            </td>
        </tr>
    </table>
<% end %>
</div>

app/views/rooms/show.html.erb
<style>
  .main {
    margin-top:100px;
  }
  
  .chats {
    border-top-style:inset;
  }
 body {
      background-image: url("<%= asset_path('joitra15.jpg') %>");
      background-size: cover;
    }
  
  h6 {
    font-size:50px;
  }
  strong {
    word-break:break-all;
  }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="main">
<div class="left-button">
</div>
<h6 class="rooms-title">ROOM</h6>
<% @entries.each do |e| %>
  <div class="user-name">
  <strong>
      <a class="rooms-user-link" href="/users/<%= e.user.id %>">
        <%= e.user.name %>さん
      </a>
  </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <div class="chat">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
          <div class="chat-face">
          </div>
          <div class="chat-hukidashi"> <strong><%= m.content %></strong> <br>
            <%= m.user.name %> <br>
            <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts">
    <%= form_for @message do |f| %>
      <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "投稿",class: 'form-submit'%>
    <% end %>
  </div>
</div>
</div>