config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'

  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :profiles
      get :chats
    end
  end
  
  
  
  resources :posts, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:index,:create,:show,:destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reverses_of_favorites, class_name: 'Favorite', foreign_key: 'post_id',dependent: :destroy
  has_many :users, through: :favorites, source: :user
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @post = current_user.posts.build
    @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to posts_url
    else
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render action: :index
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def post_params
    params.require(:post).permit(:content)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_posts.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div>
          <p class="mb-0"><%= post.content %></p>
        </div>
         <div>
           <div style="display:inline-flex">
          <% if current_user == post.user %>
            <%= link_to post_path(id: post.id), method: :delete do %>
            <i class="fas fa-trash" style="color:white;"></i>
            <% end %>
          <% end %>
          <%= render 'favorites/favorite_button', post: post %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/index.html.erb
<style>
 
  .main {
    margin-top:100px;
  }
  
  body {
      background-image: url("<%= asset_path('joitra17.jpg') %>");
      background-size: cover;
    }
</style>
<header>
  <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand"href="#">JOITRA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">USERS</a></li>
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">POST</a></li>
        <li class="nav-item"><a href="<%= rooms_path %>" class="nav-link">CHAT</a></li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<%= render 'layouts/flash_messages' %>
<div class="main">
<div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @post, local: true) do |f| %>
        <% if @post.errors.any? %>
          <div id="error_explanation">
           <ul>
            <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
           </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'posts/posts', posts: @posts %>
    </div>
</div>
</div>